#!/bin/sh
# Render the fips-exit nftables ruleset from the service catalog + env.
#
# The ruleset gates ONLY the service ports: unauthorized fips sources hitting a
# service port are redirected to the captive daemon; authorized sources reach
# the service. General fd00::/8 traffic is never touched (no drop policy), so
# the host keeps working as a normal fips node.
#
# In Phase 1 the authorized set is seeded from a static allowlist file; in
# Phase 2 the exit-agent owns the set and the acct counters live-drive billing.
#
# Env:
#   FIPS_IF         fips TUN interface        (e.g. fips0)
#   EXIT_FIPS_ADDR  this node's fips address  (services listen here)
#   CAPTIVE_PORT    local port of the captive daemon
#   SERVICES_FILE   path to services.conf     (default: ./services.conf)
#   ALLOWLIST_FILE  newline-separated fips addresses (default: ./allowlist.txt)
set -eu

FIPS_IF="${FIPS_IF:?FIPS_IF is required}"
EXIT_FIPS_ADDR="${EXIT_FIPS_ADDR:?EXIT_FIPS_ADDR is required}"
CAPTIVE_PORT="${CAPTIVE_PORT:?CAPTIVE_PORT is required}"
SERVICES_FILE="${SERVICES_FILE:-$(dirname "$0")/services.conf}"
ALLOWLIST_FILE="${ALLOWLIST_FILE:-$(dirname "$0")/allowlist.txt}"

# Collect enabled service ports.
ports=""
while read -r key port; do
    case "$key" in
        ''|\#*) continue ;;
    esac
    ports="${ports:+$ports, }$port"
done < "$SERVICES_FILE"
[ -n "$ports" ] || { echo "no services enabled in $SERVICES_FILE" >&2; exit 1; }

# Seed elements for the authorized set from the allowlist (may be empty).
elements=""
if [ -f "$ALLOWLIST_FILE" ]; then
    while read -r addr; do
        case "$addr" in
            ''|\#*) continue ;;
        esac
        elements="${elements:+$elements, }$addr"
    done < "$ALLOWLIST_FILE"
fi

cat <<EOF
#!/usr/sbin/nft -f
# Generated by render-nftables.sh — do not edit by hand.
table inet fips_exit {
    # Authorized fips source addresses (owners + whitelisted npubs, derived).
    set authorized {
        type ipv6_addr
        flags interval
$( [ -n "$elements" ] && printf '        elements = { %s }\n' "$elements" )
    }

    # Per-source byte accounting on service traffic. The exit-agent reads this
    # in Phase 2; policy accept means it only counts, never blocks.
    set acct {
        type ipv6_addr
        size 65535
        flags dynamic
        counter
    }

    # Gate: redirect unauthorized service-port traffic to the captive daemon.
    # authorized sources are accepted here (in nat = stop, packet proceeds to
    # the local service listening on that port).
    chain gate {
        type nat hook prerouting priority dstnat; policy accept;
        iifname != "$FIPS_IF" return
        ip6 daddr $EXIT_FIPS_ADDR tcp dport { $ports } ip6 saddr @authorized accept
        ip6 daddr $EXIT_FIPS_ADDR tcp dport { $ports } redirect to :$CAPTIVE_PORT
    }

    # Accounting (counts only; never drops). Both directions of authorized
    # service traffic on the fips interface.
    chain acct_in {
        type filter hook prerouting priority -150; policy accept;
        iifname "$FIPS_IF" tcp dport { $ports } ip6 saddr @authorized update @acct { ip6 saddr }
    }
    chain acct_out {
        type filter hook postrouting priority -150; policy accept;
        oifname "$FIPS_IF" tcp sport { $ports } ip6 daddr @authorized update @acct { ip6 daddr }
    }
}
EOF
