#!/bin/sh
# Render the fips-exit nftables ruleset from the service catalog + env.
#
# The ruleset gates ONLY the service ports: unauthorized fips sources hitting a
# service port are redirected to the captive daemon; authorized sources reach
# the service. General fd00::/8 traffic is never touched (no drop policy), so
# the host keeps working as a normal fips node.
#
# In Phase 1 the authorized set is seeded from a static allowlist file; in
# Phase 2 the exit-agent owns the set and the acct counters live-drive billing.
#
# Env:
#   FIPS_IF         fips TUN interface        (e.g. fips0)
#   EXIT_FIPS_ADDR  this node's fips address  (services listen here)
#   CAPTIVE_PORT    local port of the captive daemon
#   SERVICES_FILE   path to services.conf     (default: ./services.conf)
#   ALLOWLIST_FILE  newline-separated fips addresses (default: ./allowlist.txt)
#   MAX_CONNS_PER_SRC  per-source concurrent-connection ceiling (0 = disabled)
set -eu

FIPS_IF="${FIPS_IF:?FIPS_IF is required}"
EXIT_FIPS_ADDR="${EXIT_FIPS_ADDR:?EXIT_FIPS_ADDR is required}"
CAPTIVE_PORT="${CAPTIVE_PORT:?CAPTIVE_PORT is required}"
SERVICES_FILE="${SERVICES_FILE:-$(dirname "$0")/services.conf}"
ALLOWLIST_FILE="${ALLOWLIST_FILE:-$(dirname "$0")/allowlist.txt}"
MAX_CONNS_PER_SRC="${MAX_CONNS_PER_SRC:-0}"

# Collect enabled service ports.
ports=""
while read -r key port; do
    case "$key" in
        ''|\#*) continue ;;
    esac
    ports="${ports:+$ports, }$port"
done < "$SERVICES_FILE"
[ -n "$ports" ] || { echo "no services enabled in $SERVICES_FILE" >&2; exit 1; }

# Seed elements for the authorized set from the allowlist (may be empty).
elements=""
if [ -f "$ALLOWLIST_FILE" ]; then
    while read -r addr; do
        case "$addr" in
            ''|\#*) continue ;;
        esac
        elements="${elements:+$elements, }$addr"
    done < "$ALLOWLIST_FILE"
fi

# Optional per-source concurrent-connection ceiling. A filter chain (where
# ct count belongs) that drops over-limit NEW connections from authorized
# sources on service ports — so one npub/device can't exhaust the exit. Runs
# before the nat gate (lower priority number). 0 = disabled.
conn_limit_chain=""
if [ "$MAX_CONNS_PER_SRC" -gt 0 ] 2>/dev/null; then
    conn_limit_chain="
    chain conn_limit {
        type filter hook prerouting priority -160; policy accept;
        iifname \"$FIPS_IF\" ip6 daddr $EXIT_FIPS_ADDR tcp dport { $ports } ip6 saddr @authorized ct state new meter fips_connlimit { ip6 saddr ct count over $MAX_CONNS_PER_SRC } drop
    }
"
fi

cat <<EOF
#!/usr/sbin/nft -f
# Generated by render-nftables.sh — do not edit by hand.
table inet fips_exit {
    # Authorized fips source addresses (owners + whitelisted npubs, derived).
    set authorized {
        type ipv6_addr
        flags interval
$( [ -n "$elements" ] && printf '        elements = { %s }\n' "$elements" )
    }

    # Per-source byte accounting on service traffic. The exit-agent reads this
    # in Phase 2; policy accept means it only counts, never blocks.
    set acct {
        type ipv6_addr . inet_service
        size 131072
        flags dynamic
        counter
    }

    # Gate: redirect unauthorized service-port traffic to the captive daemon.
    # authorized sources are accepted here (in nat = stop, packet proceeds to
    # the local service listening on that port).
    chain gate {
        type nat hook prerouting priority dstnat; policy accept;
        iifname != "$FIPS_IF" return
        ip6 daddr $EXIT_FIPS_ADDR tcp dport { $ports } ip6 saddr @authorized accept
        ip6 daddr $EXIT_FIPS_ADDR tcp dport { $ports } redirect to :$CAPTIVE_PORT
    }

    # Accounting (counts only; never drops). Keyed on (client address, service
    # port) so usage is per-service — both directions land on the same element:
    #   inbound  client->service: (saddr, dport=service port)
    #   outbound service->client: (daddr, sport=service port)
    # so the element's byte counter is the client's total for that service.
    chain acct_in {
        type filter hook prerouting priority -150; policy accept;
        iifname "$FIPS_IF" ip6 saddr @authorized tcp dport { $ports } update @acct { ip6 saddr . tcp dport }
    }
    chain acct_out {
        type filter hook postrouting priority -150; policy accept;
        oifname "$FIPS_IF" ip6 daddr @authorized tcp sport { $ports } update @acct { ip6 daddr . tcp sport }
    }
$conn_limit_chain
}
EOF
